export const students = [
  {
    id: 1,
    name: "John Doe",
    mentorId: 1,
    ideation: 8,
    execution: 7,
    viva: 9,
    total: 24,
  },
  {
    id: 2,
    name: "Jane Smith",
    mentorId: 2,
    ideation: 6,
    execution: 8,
    viva: 7,
    total: 21,
  },
  {
    id: 3,
    name: "Alice Johnson",
    mentorId: 1,
    ideation: 9,
    execution: 6,
    viva: 8,
    total: 23,
  },
  {
    id: 4,
    name: "Michael Brown",
    mentorId: 3,
    ideation: 7,
    execution: 7,
    viva: 8,
    total: 22,
  },
  {
    id: 5,
    name: "Emily Wilson",
    mentorId: null,
    ideation: 8,
    execution: 7,
    viva: 6,
    total: 21,
  },
  {
    id: 6,
    name: "Daniel Clark",
    mentorId: null,
    ideation: 6,
    execution: 9,
    viva: 7,
    total: 22,
  },
  {
    id: 7,
    name: "Olivia Martinez",
    mentorId: null,
    ideation: 9,
    execution: 8,
    viva: 8,
    total: 25,
  },
  {
    id: 8,
    name: "William Taylor",
    mentorId: null,
    ideation: 7,
    execution: 6,
    viva: 7,
    total: 20,
  },
  {
    id: 9,
    name: "Sophia Anderson",
    mentorId: null,
    ideation: 8,
    execution: 7,
    viva: 7,
    total: 22,
  },
  {
    id: 10,
    name: "James White",
    mentorId: null,
    ideation: 9,
    execution: 8,
    viva: 9,
    total: 26,
  },
  {
    id: 11,
    name: "Emma Brown",
    mentorId: 2,
    ideation: 7,
    execution: 9,
    viva: 8,
    total: 24,
  },
  {
    id: 12,
    name: "Noah Garcia",
    mentorId: 3,
    ideation: 8,
    execution: 7,
    viva: 7,
    total: 22,
  },
  {
    id: 13,
    name: "Isabella Martinez",
    mentorId: 1,
    ideation: 9,
    execution: 8,
    viva: 9,
    total: 26,
  },
  {
    id: 14,
    name: "Liam Rodriguez",
    mentorId: 4,
    ideation: 8,
    execution: 8,
    viva: 8,
    total: 24,
  },
  {
    id: 15,
    name: "Ava Hernandez",
    mentorId: 2,
    ideation: 7,
    execution: 9,
    viva: 7,
    total: 23,
  },
];

export const mentors = [
  { id: 1, name: "Dr. Sarah Johnson" },
  { id: 2, name: "Prof. Michael Smith" },
  { id: 3, name: "Dr. Emily Davis" },
  { id: 4, name: "Prof. David Wilson" },
  { id: 5, name: "Dr. Jennifer Brown" },
  { id: 6, name: "Prof. Christopher Martinez" },
  { id: 7, name: "Dr. Jessica Thompson" },
  { id: 8, name: "Prof. Matthew Lee" },
  { id: 9, name: "Dr. Laura Garcia" },
  { id: 10, name: "Prof. Daniel Rodriguez" },
];
